// Code generated by protoc-gen-gogo.
// source: github.com/openshift/api/console/v1beta1/generated.proto
// DO NOT EDIT!

/*
	Package v1beta1 is a generated protocol buffer package.

	It is generated from these files:
		github.com/openshift/api/console/v1beta1/generated.proto

	It has these top-level messages:
		ClusterInfo
		ConsoleConfiguration
		Customization
*/
package v1beta1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func (m *ClusterInfo) Reset()                    { *m = ClusterInfo{} }
func (*ClusterInfo) ProtoMessage()               {}
func (*ClusterInfo) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{0} }

func (m *ConsoleConfiguration) Reset()                    { *m = ConsoleConfiguration{} }
func (*ConsoleConfiguration) ProtoMessage()               {}
func (*ConsoleConfiguration) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{1} }

func (m *Customization) Reset()                    { *m = Customization{} }
func (*Customization) ProtoMessage()               {}
func (*Customization) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{2} }

func init() {
	proto.RegisterType((*ClusterInfo)(nil), "github.com.openshift.api.console.v1beta1.ClusterInfo")
	proto.RegisterType((*ConsoleConfiguration)(nil), "github.com.openshift.api.console.v1beta1.ConsoleConfiguration")
	proto.RegisterType((*Customization)(nil), "github.com.openshift.api.console.v1beta1.Customization")
}
func (m *ClusterInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.ConsolePublicURL)))
	i += copy(dAtA[i:], m.ConsolePublicURL)
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.MasterPublicURL)))
	i += copy(dAtA[i:], m.MasterPublicURL)
	dAtA[i] = 0x1a
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.LogoutPublicURL)))
	i += copy(dAtA[i:], m.LogoutPublicURL)
	return i, nil
}

func (m *ConsoleConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsoleConfiguration) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ServingInfo.Size()))
	n1, err := m.ServingInfo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ClusterInfo.Size()))
	n2, err := m.ClusterInfo.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x1a
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Customization.Size()))
	n3, err := m.Customization.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	return i, nil
}

func (m *Customization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Customization) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.LogoIconName)))
	i += copy(dAtA[i:], m.LogoIconName)
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.DocumentationURL)))
	i += copy(dAtA[i:], m.DocumentationURL)
	return i, nil
}

func encodeFixed64Generated(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Generated(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ClusterInfo) Size() (n int) {
	var l int
	_ = l
	l = len(m.ConsolePublicURL)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.MasterPublicURL)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.LogoutPublicURL)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *ConsoleConfiguration) Size() (n int) {
	var l int
	_ = l
	l = m.ServingInfo.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.ClusterInfo.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Customization.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *Customization) Size() (n int) {
	var l int
	_ = l
	l = len(m.LogoIconName)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.DocumentationURL)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ClusterInfo) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClusterInfo{`,
		`ConsolePublicURL:` + fmt.Sprintf("%v", this.ConsolePublicURL) + `,`,
		`MasterPublicURL:` + fmt.Sprintf("%v", this.MasterPublicURL) + `,`,
		`LogoutPublicURL:` + fmt.Sprintf("%v", this.LogoutPublicURL) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConsoleConfiguration) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConsoleConfiguration{`,
		`ServingInfo:` + strings.Replace(strings.Replace(this.ServingInfo.String(), "HTTPServingInfo", "github_com_openshift_api_config_v1.HTTPServingInfo", 1), `&`, ``, 1) + `,`,
		`ClusterInfo:` + strings.Replace(strings.Replace(this.ClusterInfo.String(), "ClusterInfo", "ClusterInfo", 1), `&`, ``, 1) + `,`,
		`Customization:` + strings.Replace(strings.Replace(this.Customization.String(), "Customization", "Customization", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Customization) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Customization{`,
		`LogoIconName:` + fmt.Sprintf("%v", this.LogoIconName) + `,`,
		`DocumentationURL:` + fmt.Sprintf("%v", this.DocumentationURL) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ClusterInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsolePublicURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsolePublicURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MasterPublicURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MasterPublicURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogoutPublicURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LogoutPublicURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsoleConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsoleConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsoleConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServingInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ServingInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClusterInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Customization", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Customization.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Customization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Customization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Customization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogoIconName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LogoIconName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocumentationURL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocumentationURL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGenerated(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGenerated = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/openshift/api/console/v1beta1/generated.proto", fileDescriptorGenerated)
}

var fileDescriptorGenerated = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0x9b, 0x71, 0x40, 0x38, 0x9b, 0x36, 0x85, 0x21, 0xa6, 0x1e, 0x32, 0xd4, 0xd3, 0x2e,
	0xb3, 0xd5, 0x8e, 0x97, 0x5e, 0x69, 0x77, 0x60, 0x52, 0x41, 0x53, 0x18, 0x17, 0x6e, 0x6e, 0xe6,
	0xb8, 0x66, 0xb1, 0x1d, 0xc5, 0x76, 0x25, 0x38, 0xf1, 0x0d, 0xe0, 0x63, 0xf5, 0xb8, 0xe3, 0xb8,
	0x4c, 0x34, 0x48, 0x7c, 0x0e, 0x14, 0x63, 0x2d, 0x6f, 0x6c, 0xc0, 0x2d, 0x79, 0x9e, 0xe7, 0xf7,
	0x7f, 0x5e, 0xfc, 0x07, 0x63, 0xca, 0xf4, 0xc2, 0xcc, 0x61, 0x2c, 0x39, 0x92, 0x19, 0x11, 0x6a,
	0xc1, 0x12, 0x8d, 0x70, 0xc6, 0x50, 0x2c, 0x85, 0x92, 0x29, 0x41, 0xcb, 0xe1, 0x9c, 0x68, 0x3c,
	0x44, 0x94, 0x08, 0x92, 0x63, 0x4d, 0xce, 0x61, 0x96, 0x4b, 0x2d, 0x83, 0x83, 0x8a, 0x84, 0x37,
	0x24, 0xc4, 0x19, 0x83, 0x8e, 0x84, 0x8e, 0xec, 0x1f, 0xd6, 0x7a, 0x50, 0x49, 0x25, 0xb2, 0x02,
	0x73, 0x93, 0xd8, 0x3f, 0xfb, 0x63, 0xbf, 0x7e, 0x0b, 0xf7, 0x47, 0x77, 0x8d, 0x94, 0x30, 0x8a,
	0x96, 0x9d, 0x61, 0xfa, 0x4f, 0x2f, 0xc6, 0x0a, 0x32, 0x59, 0x56, 0x71, 0x1c, 0x2f, 0x98, 0x20,
	0xf9, 0x47, 0x94, 0x5d, 0xd0, 0x32, 0xa0, 0x10, 0x27, 0x1a, 0xff, 0x89, 0x42, 0xb7, 0x51, 0xb9,
	0x11, 0x9a, 0x71, 0xd2, 0x01, 0x9e, 0xff, 0x0d, 0x50, 0xf1, 0x82, 0x70, 0xdc, 0xe1, 0x8e, 0x6e,
	0xe3, 0x8c, 0x66, 0x29, 0x62, 0x42, 0x2b, 0x9d, 0xb7, 0xa1, 0xc1, 0x37, 0x0f, 0xf8, 0xd3, 0xd4,
	0x28, 0x4d, 0xf2, 0x13, 0x91, 0xc8, 0xe0, 0x18, 0xec, 0xb8, 0xcb, 0x9e, 0x9a, 0x79, 0xca, 0xe2,
	0x77, 0xd1, 0x6c, 0xcf, 0x7b, 0xe2, 0x1d, 0x3c, 0x98, 0xec, 0xad, 0xae, 0xf7, 0x7b, 0xc5, 0xf5,
	0xfe, 0xce, 0xb4, 0x95, 0x8f, 0x3a, 0x44, 0xf0, 0x12, 0x6c, 0x73, 0x5c, 0x6a, 0x56, 0x22, 0x1b,
	0x56, 0xe4, 0xb1, 0x13, 0xd9, 0x7e, 0xdd, 0x4c, 0x47, 0xed, 0xfa, 0x52, 0x22, 0x95, 0x54, 0x1a,
	0x5d, 0x49, 0xdc, 0x6b, 0x4a, 0xcc, 0x9a, 0xe9, 0xa8, 0x5d, 0x3f, 0xf8, 0xb9, 0x01, 0x76, 0xdd,
	0xb0, 0x53, 0xfb, 0xa8, 0x26, 0xc7, 0x9a, 0x49, 0x11, 0x7c, 0x00, 0xbe, 0x22, 0xf9, 0x92, 0x09,
	0x5a, 0xee, 0x6c, 0xf7, 0xf3, 0x47, 0x47, 0xf0, 0x2e, 0xaf, 0x25, 0x8c, 0xc2, 0xe5, 0x10, 0xbe,
	0x3a, 0x3b, 0x3b, 0x7d, 0x5b, 0xa1, 0x93, 0x87, 0x6e, 0x18, 0xbf, 0x16, 0x8c, 0xea, 0xe2, 0x41,
	0x0a, 0xfc, 0xb8, 0xba, 0xaf, 0x3d, 0x83, 0x3f, 0x7a, 0x06, 0xff, 0xd5, 0xd7, 0xb0, 0xf6, 0x38,
	0x55, 0xb7, 0x5a, 0x30, 0xaa, 0xcb, 0x07, 0x1a, 0x6c, 0xc5, 0x46, 0x69, 0xc9, 0xd9, 0x27, 0xbb,
	0xaa, 0xbd, 0x99, 0x3f, 0x7a, 0xf1, 0x1f, 0xfd, 0xea, 0xf8, 0xe4, 0x91, 0xeb, 0xb8, 0xd5, 0x08,
	0x47, 0xcd, 0x26, 0x83, 0x2f, 0x1e, 0x68, 0x16, 0x04, 0x63, 0xb0, 0x59, 0xbe, 0xc6, 0x49, 0x2c,
	0xc5, 0x1b, 0xcc, 0x89, 0xb3, 0xd0, 0xae, 0x53, 0xdb, 0x9c, 0xd5, 0x72, 0x51, 0xa3, 0xb2, 0x34,
	0xe0, 0xb9, 0x8c, 0x0d, 0x27, 0x42, 0x5b, 0xa9, 0xca, 0x3b, 0x37, 0x06, 0x3c, 0x6e, 0xe5, 0xa3,
	0x0e, 0x31, 0x39, 0x5c, 0xad, 0xc3, 0xde, 0xe5, 0x3a, 0xec, 0x5d, 0xad, 0xc3, 0xde, 0xe7, 0x22,
	0xf4, 0x56, 0x45, 0xe8, 0x5d, 0x16, 0xa1, 0x77, 0x55, 0x84, 0xde, 0xf7, 0x22, 0xf4, 0xbe, 0xfe,
	0x08, 0x7b, 0xef, 0xef, 0xbb, 0xa5, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xed, 0xbd, 0x29, 0x96,
	0xa1, 0x04, 0x00, 0x00,
}
